### ISSUE TITLE
Auto-generate command documentation

### ISSUE THREAD

**Issue by fractal161** [professor-l/classic-tetris-project#111]
After briefly looking at existing solutions, I think the best fit for the current project is to implement this ourselves. Since the existing commands.md is pretty simply formatted, this shouldn't be too bad. The larger purpose is to add docstrings to all commands, which should be a matter of copy/paste.

**Comment by michaelelin** [comment]
My initial intent was to pass all information necessary to render the help docs into the `@Command.register` decorator (and potentially pass in a markdown-formatted multiline description as well). Seems like docstrings could work just as well though.

Generating markdown for each command seems like a good goal. We could probably dynamically generate the docs, cache the markdown/HTML, and serve it up from the website too.
In order to match what's currently in `COMMANDS.md`, we might also need to assign a "category" to each command so they can be grouped together.

**Comment by fractal161** [comment]
Added in https://github.com/professor-l/classic-tetris-project/pull/118.
